### ISSUE TITLE
US 02.02.03 - User contact information

### ISSUE THREAD

**Issue by mkols1** [CMPUT301W24T23/Checkin#15]
- As an attendee, I want to update information such as name, homepage, and contact information on my profile.
	Features:
		- User contact information
	Size: 1
	Risk: Low

**Comment by anurag1102990** [comment]
I have implemented the update method in the Attendee class but confused if I will be implementing it when the update/Edit button is pressed on the XML or not as that particular XML part has not been done yet. Or I can made that XML part also and add that functionality to it so to make it fully functional.

**Comment by mkols1** [comment]
Sukh is assigned the [profile picture upload](https://github.com/CMPUT301W24T23/Checkin/issues/13#issue-2138729793) so I guess you two could talk and decide how you'll implement both features since they're both related to changing attendee data.
If you both decide to implement both features on the same fragment in the app then you'd have to decide which of you will make the front end or if you both decide to make them in separate fragments then you could each do your own parts.

**Comment by sukhman1902** [comment]
Hey, i guess it would be really easy for both of us to work on it together as our issues are connected. let me know what time is good for you to work together.
