### ISSUE TITLE
US 01.01.01 - Event Creation, QR Code Generation

### ISSUE THREAD

**Issue by mkols1** [CMPUT301W24T23/Checkin#2]
- As an organizer, I want to create a new event and generate a unique QR code for attendee check-ins.
- Features:
		- Event Creation
		- QR Code Generation
	Size: 3
	Risk: Low

**Comment by rsrashid** [comment]
waiting for this issue to be made to add this feature: US 03.02.01 - Geolocation tracking toggle

**Comment by samiras24** [comment]
Added firebase integration for adding an event, still requires integration of qr code
